name: "Download Release"
description: "Get lestes release an ddownload It"

inputs:
  repo_token:
    description: "Le token github"
    required: true
  owner:
    description: "The Github user or organization that owns the repository"
    required: false
  repo:
    description: "The repository name"
    required: false
  repository:
    description: "The repository name in full"
    required: false
  excludes:
    description: "Types of releases to exclude (e.g. pre-release)"
    required: false
outputs:
  release:
    description: "Latest release"
runs:
  using: "node12"
  main: "index.js"
