# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DOPRR.COM CD
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      GITHUB_TOKEN: ${{ secrets.DOPRR_TOKEN }}
      NODE_VERSION: "v14.15.4"
      VERSION_TYPE: ""
      VERSION_TAG: ""
      commitmsg: ""
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - name: front
            path: front
            localfolder: dist
            workspace: /home/runner/work/doprr.com/doprr.com/front
            installNpm: "true"
            restartService: "true"
          - name: back
            path: back
            workspace: /home/runner/work/doprr.com/doprr.com/back
            localfolder: dist
            installNpm: "false"
            restartService: "false"

    steps:
      - name: Display runner information
        run: |
          echo "CI = ${CI}"
          echo "GITHUB_ACTION = ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS = ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR = ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH = ${GITHUB_EVENT_PATH}"
          echo "GITHUB_REF = ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY = ${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_ID = ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_SHA = ${GITHUB_SHA}"
          echo "GITHUB_WORKFLOW = ${GITHUB_WORKFLOW}"
          echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}"
          echo "HOME = ${HOME}"
          echo "HOSTNAME = ${HOSTNAME}"
          echo "USER = ${USER}"
          echo "ID = $(id)"
          git --version
          git lfs version
          echo "Amount of free and used memory:"
          free -h
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION }}
          cache: "npm"
      - name: Npm install(npm ci)
        run: |
          cd $GITHUB_WORKSPACE/${{matrix.path}}
          npm ci
      - name: Npm Build(npm ci)
        run: |
          cd $GITHUB_WORKSPACE/${{matrix.path}}
          npm run build
