on:
  workflow_run:
    workflows: ["DOPRR.COM CD"]
    types:
      - completed

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      GITHUB_TOKEN: ${{ secrets.DOPRR_TOKEN }}
      NODE_VERSION: "v14.15.4"
      VERSION_TYPE: "patch"
      VERSION_TAG: ""
      commitmsg: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
