on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to deploy
        options: 
        - PROD
        - DEV
     
      qbp_admin:
        type: boolean
        description: deployer l'admin
      qbp_admin_seller:
        type: boolean
        default: 'true' 
        description: deployer l'admin_seller
      qbp:
        type: boolean
        description: deployer le front
      qbp_service:
        type: boolean
        description: deployer le service
    
name: DOPRRR release
jobs:
  build:
    name: Build , update Version an publish to Prod server
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      GITHUB_TOKEN: ${{secrets.DOPRR_TOKEN}}
      NODE_VERSION: "v14.15.4"
      VERSION_TYPE: "patch"
      VERSION_TAG: ""
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Display runner information
        run: |
          echo ${{github.actor}}
          echo "CI = ${CI}"
          echo "GITHUB_ACTION = ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS = ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR = ${GITHUB_ACTOR}"
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH = ${GITHUB_EVENT_PATH}"
          echo "GITHUB_REF = ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY = ${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_ID = ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_SHA = ${GITHUB_SHA}"
          echo "GITHUB_WORKFLOW = ${GITHUB_WORKFLOW}"
          echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}"
          echo "HOME = ${HOME}"
          echo "HOSTNAME = ${HOSTNAME}"
          echo "USER = ${USER}"
          echo "ID = $(id)"
          git --version
          git lfs version
          echo "Amount of free and used memory:"
          free -h
      - name: Install action modules
        run: |
          cd $GITHUB_WORKSPACE/download-release-action
          npm i
      - name: Download release
        uses: ./download-release-action
        id: hello
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          repo: "doprr.com"
          owner: "diegopatinodoprr"

      - name: Get the output time
        run: |
          echo "Release name: ${{ steps.hello.outputs.name }}"
          echo "Release download tar: ${{ steps.hello.outputs.tarball_url }}"
          echo "Release download zip:  ${{ steps.hello.outputs.zipball_url }}"
      - name: Download release
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "diegopatinodoprr/doprr.com"
          latest: true
          out-file-path: "downloadRelease"
      - name: Ls als
        run: |
          echo ls
          ls -als
          ls -l
          dir
          cd downloadRelease
          ls
          dir
          ls -l
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq ./doprr.zip -d unzipedFiles
      - name: Display unzip results
        run: |
          echo ls -als
          echo dir
          echo dir unzipedFiles

#
